remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-redirect-from

locale: "en-US"
title: "Modeling and Simulating Software Architectures"
title_separator: "-"
subtitle: "The Palladio Approach"
name: "The Palladio Approach"
description: "Palladio. The Quality Software People."
breadcrumbs: true
ermalink: /:categories/:title/
paginate: 0
paginate_path: /page:num/
timezone: # "Europe/Berlin"
words_per_minute: 200
comments:
  provider: false
atom_feed:
  path: blank
  hide: true
search: false
analytics:
  provider: false
